server:
  servlet:
    context-path: ${CONTEXT_PATH:/}

spring:
  application:
    name: quicklib

jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
