server:
  servlet:
    context-path: ${CONTEXT_PATH:/}
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: ../v3/api-docs
  api-docs:
    path: /v3/api-docs

spring:
  application:
    name: quicklib

jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

# CORS configuration
frontend:
  url: ${APP_URL}
